### ISSUE TITLE
{ eventName | id } does not render in markdown

### ISSUE THREAD

**Issue by zhaofeng-shu33** [v2land/v2land-redstone#126]
In `docs/api/Event.md`

**Comment by incrediblink** [comment]
Thank you for pointing this out. We have created a new pull request to tackle this issue. If you want to deploy your own v2land website, we recommend you to join either our [Slack channel](https://join.slack.com/t/v2land/shared_invite/enQtMzA4NTE1ODQzODU2LTMzNjMyZjdiYWU3OGQyZTI1YzA2ZTliNDBlMzY1MTA0N2RhYjBmZDJhNTY2N2IxMDdmMmJkNWY1NjcwZmY0NGQ) or [Telegram group chat](https://t.me/joinchat/AwWDRE3b5ZasxWROvz4y7w), as the backend documentation has not been updated very recently, and you might run into some unexpected problems. We would also be thrilled if you'd like to contribute to the development of v2land with us.

简而言之，希望你能加入我们的社群，跟我们一起建设浪潮w
