### ISSUE TITLE
Add unit tests and CI

### ISSUE THREAD

**Issue by vincentdchan** [v2land/v2land-redstone#7]

**Comment by incrediblink** [comment]
= = 我一直很懒得写单元测试（可能也是我项目经常到头来一团糟的原因），Vincent 这方面经验丰富吗？

**Comment by vincentdchan** [comment]
@incrediblink 嗯，让我来写吧，等把 api 搭建起来之后再弄

**Comment by vincentdchan** [comment]
单元测试框架已经搭起来了，直接用`make test`就可以测试，测试完整性测试也已经加上了
